import os
from dotenv import load_dotenv

from src.component.feature_store_api import FeatureGroupConfig, FeatureViewConfig
from src.paths import PARENT_DIR

# Load key-value pairs from .env file located in the parent directory
load_dotenv(PARENT_DIR / ".env")

try:
    HOPSWORKS_PROJECT_NAME = os.environ["HOPSWORKS_PROJECT_NAME"]
    HOPSWORKS_API_KEY = os.environ["HOPSWORKS_API_KEY"]
except:
    raise Exception(
        "Create an .env file on the project root with the HOPSWORKS_PROJECT_NAME and HOPSWORKS_API_KEY"
    )

# Feature group for raw demand data
FEATURE_GROUP_NAME = "electricity_demand_feature_group"
FEATURE_GROUP_VERSION = 1
FEATURE_GROUP_METADATA = FeatureGroupConfig(
    name=FEATURE_GROUP_NAME,
    version=FEATURE_GROUP_VERSION,
    description="Feature group with hourly time-series data of historical demand values",
    primary_key=["sub_region_code", "seconds"],
    event_time="date",
    online_enabled=True,
)

# Feature view for model input
FEATURE_VIEW_NAME = "electricity_demand_feature_view"
FEATURE_VIEW_VERSION = 1
FEATURE_VIEW_METADATA = FeatureViewConfig(
    name=FEATURE_VIEW_NAME,
    version=FEATURE_VIEW_VERSION,
    feature_group=FEATURE_GROUP_METADATA,
)

# Model name and version
MODEL_NAME = "electricity_demand_predictor_next_hour"
MODEL_VERSION = 1

# Feature group for storing model predictions (✅ Fixed schema)
FEATURE_GROUP_MODEL_PREDICTIONS = "model_predictions_feature_group2"
FEATURE_GROUP_PREDICTIONS_METADATA = FeatureGroupConfig(
    name=FEATURE_GROUP_MODEL_PREDICTIONS,
    version=1,
    description="Predictions generated by our production model",
    primary_key=["sub_region_code", "seconds"],
    event_time="date",
)

# Feature view for predictions
FEATURE_VIEW_MODEL_PREDICTIONS = "model_predictions_feature_view2"
FEATURE_VIEW_PREDICTIONS_METADATA = FeatureViewConfig(
    name=FEATURE_VIEW_MODEL_PREDICTIONS,
    version=1,
    feature_group=FEATURE_GROUP_PREDICTIONS_METADATA,
)

# Monitoring (optional)
MONITORING_FV_NAME = "monitoring_feature_view"
MONITORING_FV_VERSION = 1

# Model input length and training config
N_FEATURES = 24 * 28  # 28 days, hourly
N_HYPERPARAMETER_SEARCH_TRIALS = 5
MAX_MAE = 400
